import os

from odoo import tools


LOCAL_GOOGLE_FONTS_CACHE_DIR_PATH = os.path.join(
    tools.config["data_dir"], "google_fonts"
)
LOCAL_GOOGLE_FONTS_CACHE_DIR_PATH = os.getenv(
    "ODOO_LOCAL_GOOGLE_FONTS_CACHE_DIR_PATH", LOCAL_GOOGLE_FONTS_CACHE_DIR_PATH
)

GOOGLE_FONT_STYLESHEETS_PATH = os.getenv(
    "ODOO_GOOGLE_FONT_STYLESHEETS_PATH", LOCAL_GOOGLE_FONTS_CACHE_DIR_PATH
)
GOOGLE_FONTS_PATH = os.path.join(LOCAL_GOOGLE_FONTS_CACHE_DIR_PATH, "gstatic")
GOOGLE_FONTS_PATH = os.getenv("ODOO_GOOGLE_FONTS_PATH", GOOGLE_FONTS_PATH)

DONT_DOWNLOAD_GOOGLE_FONTS_ON_MODULE_INSTALL = os.getenv("ODOO_DONT_DOWNLOAD_GOOGLE_FONTS_ON_MODULE_INSTALL", False)